# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lakshminarayanan Sadagopan
tagline:          The website of Lakshminarayanan Sadagopan
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Lakshminarayanan Sadagopan
  url:            https://twitter.com/lsadagopan
  email:          laxmynarain@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/laxmynarain.github.io
