# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The constant learner
tagline:          The website of Lakshminarayanan Sadagopan
url:              http://laxmynarain.github.io/
paginate:         1
baseurl:          http://laxmynarain.github.io/
author:
  name:           Lakshminarayanan Sadagopan
  url:            https://twitter.com/lsadagopan
  email:          laxmynarain@gmail.com
comments:         True
# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/laxmynarain.github.io/

pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml','Resume':'/resume', 'Projects':'projects'}